spring:
  application:
    name: kitchensink
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:admin123@localhost:27017/kitchensinkdb?authSource=admin}

server:
  port: ${PORT:9092}

jwt:
  secret: ${JWT_SECRET:uN8L6nqFqVpO3X7Jz9KmL0N7vYTxIqI7FiP6v9QIsxk=}
  expiration-ms: ${JWT_EXPIRATION_MS:1800000}

app:
  bootstrap-admin:
    enabled: ${APP_BOOTSTRAP_ADMIN_ENABLED:false}
    name: ${APP_BOOTSTRAP_ADMIN_NAME:John Smith}
    email: ${APP_BOOTSTRAP_ADMIN_EMAIL:john.smith@mailinator.com}
    phone: ${APP_BOOTSTRAP_ADMIN_PHONE:2125551212}
    password: ${APP_BOOTSTRAP_ADMIN_PASSWORD:Welcome@123}
    roles: ${APP_BOOTSTRAP_ADMIN_ROLES:ROLES_ADMIN}
